version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres:15
    command: [ "postgres", "-c", "log_statement=all" ]
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  db_data: ~
